// 语言包定义
const languagePack = {
    'en': {
        // 导航栏
        'nav.home': 'Home',
        'nav.games': 'Games',
        'nav.about': 'About',
        'nav.privacy': 'Privacy Policy',
        'nav.contact': 'Contact',
        
        // 英雄区域
        'hero.title': 'Creating Immersive Gaming Experiences',
        'hero.subtitle': 'LIHUIGAMES is an independent game developer specializing in action game development, dedicated to creating captivating and immersive gaming experiences for players worldwide.',
        'hero.button': 'Explore My Games',
        
        // 游戏区域
        'games.title': 'My Games',
        'games.subtitle': 'Discover my portfolio of innovative and engaging games across multiple platforms.',
        'games.game1.title': 'Princess Guard',
        'games.game1.description': 'A action role-playing game set in a dystopian future, telling the story of the collision between guardians and the protected.',
        'games.game2.title': 'Nine Nights',
        'games.game2.description': 'Explore a vast fantasy world filled with Chinese martial arts and epic quests.',
        'games.game3.title': 'Ant Jump',
        'games.game3.description': 'A cartoon platform-jumping game that challenges players is extreme survival skills in a cartoon world full of traps and dangers.',
        'games.learnMore': 'Learn More',
        
        // 关于我们区域
        'about.title': 'About LIHUIGAMES',
        'about.subtitle': 'Learn more about me and my mission to create unforgettable gaming experiences.',
        'about.ourStory': 'My Story',
        'about.story1': 'I am an independent game developer and also a seasoned action game player.',
        'about.story2': 'For many years, I have been passionate about action games, and that is why I only focus on making action games.',
        'about.story3': 'I hope to express my love and thoughts about games in my own games, and at the same time, I also hope to provide some fresh and interesting gaming experiences for gamers.',
        'about.joinTeam': 'Contact Me',
        
        // 隐私政策区域
        'privacy.title': 'Privacy Policy',
        'privacy.subtitle': 'Your privacy is important to us. Learn how we collect, use, and protect your information.',
        'privacy.section1.title': 'Information We Collect',
        'privacy.section1.p1': 'We collect information to provide better services to our users. The types of information we collect include:',
        'privacy.section1.li1.title': 'Personal Information:',
        'privacy.section1.li1.text': 'When you create an account, we may ask for personal information such as your name, email address, and date of birth.',
        'privacy.section1.li2.title': 'Game Data:',
        'privacy.section1.li2.text': 'We collect data about your gameplay, including progress, achievements, and in-game purchases.',
        'privacy.section1.li3.title': 'Device Information:',
        'privacy.section1.li3.text': 'We collect device-specific information such as hardware model, operating system, and unique device identifiers.',
        'privacy.section1.li4.title': 'Log Information:',
        'privacy.section1.li4.text': 'When you use our services, we automatically collect and store certain information in server logs.',
        'privacy.section2.title': 'How We Use Information',
        'privacy.section2.p1': 'We use the information we collect for the following purposes:',
        'privacy.section2.li1': 'To provide, maintain, and improve our games and services',
        'privacy.section2.li2': 'To develop new games and features',
        'privacy.section2.li3': 'To provide customer support and respond to inquiries',
        'privacy.section2.li4': 'To send important notices, such as updates to our terms and policies',
        'privacy.section2.li5': 'To detect, prevent, and address technical issues and security vulnerabilities',
        'privacy.section2.li6': 'To personalize your gaming experience',
        'privacy.section3.title': 'Information Sharing',
        'privacy.section3.p1': 'We do not sell your personal information to third parties. We may share your information in the following limited circumstances:',
        'privacy.section3.li1': 'With your consent',
        'privacy.section3.li2': 'With service providers who assist us in operating our services (subject to confidentiality agreements)',
        'privacy.section3.li3': 'For legal reasons, when we believe in good faith that disclosure is necessary to comply with applicable laws or legal processes',
        'privacy.section3.li4': 'To protect the rights, property, or safety of LIHUIGAMES, our users, or the public',
        'privacy.section4.title': 'Data Security',
        'privacy.section4.p1': 'We implement appropriate technical and organizational security measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction.',
        'privacy.section4.p2': 'While we strive to use commercially acceptable means to protect your personal information, we cannot guarantee its absolute security.',
        'privacy.section5.title': 'Children\'s Privacy',
        'privacy.section5.p1': 'Our services are not directed to individuals under the age of 13. We do not knowingly collect personal information from children under 13. If we become aware that a child under 13 has provided us with personal information, we will take steps to delete such information.',
        'privacy.section6.title': 'Changes to This Policy',
        'privacy.section6.p1': 'We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last Updated" date.',
        'privacy.section6.p2': 'You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.',
        'privacy.section7.title': 'Contact Me',
        'privacy.section7.p1': 'If you have any questions about this Privacy Policy, please contact me:',
		 'privacy.section7.li2.link': 'Contact Me',
        'privacy.section7.li1': 'By email: lihuigame888@163.com',
        'privacy.section7.li2': 'By visiting this page on our website: ',
        'privacy.lastUpdated': 'Last Updated: June 15, 2025',
        
        // 联系区域
        'contact.title': 'Contact Me',
        'contact.subtitle': 'Have questions or want to collaborate? Get in touch with our team.',
        'contact.form.name': 'Name',
        'contact.form.namePlaceholder': 'Your Name',
        'contact.form.email': 'Email',
        'contact.form.emailPlaceholder': 'Your Email',
        'contact.form.subject': 'Subject',
        'contact.form.subjectPlaceholder': 'Subject',
        'contact.form.message': 'Message',
        'contact.form.messagePlaceholder': 'Your Message',
        'contact.form.submit': 'Send Message',
        
        // 页脚
        'footer.description': 'Creating immersive gaming experiences that captivate players and push the boundaries of innovation.',
        'footer.quickLinks': 'Quick Links',
        'footer.support': 'Support',
        'footer.faq': 'FAQ',
        'footer.terms': 'Terms of Service',
        'footer.careers': 'Careers',
        'footer.contactInfo': 'Contact Info',
        'footer.rights': 'All rights reserved.'
    },
    'zh': {
        // 导航栏
        'nav.home': '首页',
        'nav.games': '游戏',
        'nav.about': '关于我',
        'nav.privacy': '隐私政策',
        'nav.contact': '联系我',
        
        // 英雄区域
        'hero.title': '创造沉浸式游戏体验',
        'hero.subtitle': 'LIHUIGAMES是一家专注于动作游戏开发的独立游戏开发商，致力于为全球玩家创造迷人而身临其境的游戏体验。',
        'hero.button': '探索我的游戏',
        
        // 游戏区域
        'games.title': '我的游戏',
        'games.subtitle': '发现我在多个平台上的创新和引人入胜的游戏组合。',
        'games.game1.title': '公主守护',
        'games.game1.description': '一款设定在反乌托邦未来的二次元动作角色扮演游戏，讲述守护者与被守护者碰撞的故事。',
        'games.game2.title': '九夜刺狼',
        'games.game2.description': '探索一个充满中国武侠和史诗任务的广阔奇幻世界。',
        'games.game3.title': '蚂蚁不跳',
        'games.game3.description': '一款卡通平台跳跃游戏，在充满陷阱和危险的卡通世界挑战玩家的极限生存能力。',
        'games.learnMore': '了解更多',
        
        // 关于我们区域
        'about.title': '关于LIHUIGAMES',
        'about.subtitle': '了解更多关于我以及我创造难忘游戏体验的使命。',
        'about.ourStory': '我的故事',
        'about.story1': '我是一名独立游戏开发者，同时也是一名资深动作类游戏玩家。',
        'about.story2': '多年来我一直钟情于动作类游戏，这也是我只是专注于制作动作类游戏的原因。',
        'about.story3': '我希望在自己的游戏中表达我对于游戏的热爱和思考，同时也希望能够为游戏玩家们提供一些新鲜有趣的游戏体验。',
        'about.joinTeam': '联系我',
        
        // 隐私政策区域
        'privacy.title': '隐私政策',
        'privacy.subtitle': '您的隐私对我们很重要。了解我们如何收集、使用和保护您的信息。',
        'privacy.section1.title': '我们收集的信息',
        'privacy.section1.p1': '我们收集信息是为了向用户提供更好的服务。我们收集的信息类型包括：',
        'privacy.section1.li1.title': '个人信息：',
        'privacy.section1.li1.text': '当您创建帐户时，我们可能会要求提供个人信息，如您的姓名、电子邮件地址和出生日期。',
        'privacy.section1.li2.title': '游戏数据：',
        'privacy.section1.li2.text': '我们收集有关您游戏玩法的数据，包括进度、成就和游戏内购买。',
        'privacy.section1.li3.title': '设备信息：',
        'privacy.section1.li3.text': '我们收集设备特定信息，如硬件型号、操作系统和唯一设备标识符。',
        'privacy.section1.li4.title': '日志信息：',
        'privacy.section1.li4.text': '当您使用我们的服务时，我们会自动收集并存储服务器日志中的某些信息。',
        'privacy.section2.title': '我们如何使用信息',
        'privacy.section2.p1': '我们使用收集的信息用于以下目的：',
        'privacy.section2.li1': '提供、维护和改进我们的游戏和服务',
        'privacy.section2.li2': '开发新游戏和功能',
        'privacy.section2.li3': '提供客户支持并回应查询',
        'privacy.section2.li4': '发送重要通知，例如我们的条款和政策的更新',
        'privacy.section2.li5': '检测、预防和解决技术问题和安全漏洞',
        'privacy.section2.li6': '个性化您的游戏体验',
        'privacy.section3.title': '信息共享',
        'privacy.section3.p1': '我们不会将您的个人信息出售给第三方。我们可能在以下有限情况下共享您的信息：',
        'privacy.section3.li1': '经您同意',
        'privacy.section3.li2': '与帮助我们运营服务的服务提供商共享（受保密协议约束）',
        'privacy.section3.li3': '出于法律原因，当我们善意认为披露是遵守适用法律或法律程序所必需的',
        'privacy.section3.li4': '为保护LIHUIGAMES、我们的用户或公众的权利、财产或安全',
        'privacy.section4.title': '数据安全',
        'privacy.section4.p1': '我们实施适当的技术和组织安全措施，以保护您的个人信息免受未经授权的访问、更改、披露或破坏。',
        'privacy.section4.p2': '虽然我们努力使用商业上可接受的方式来保护您的个人信息，但我们无法保证其绝对安全。',
        'privacy.section5.title': '儿童隐私',
        'privacy.section5.p1': '我们的服务不针对13岁以下的个人。我们不会故意收集13岁以下儿童的个人信息。如果我们意识到13岁以下的儿童向我们提供了个人信息，我们将采取措施删除此类信息。',
        'privacy.section6.title': '本政策的变更',
        'privacy.section6.p1': '我们可能会不时更新我们的隐私政策。我们将通过在此页面上发布新的隐私政策并更新"最后更新"日期来通知您任何更改。',
        'privacy.section6.p2': '建议您定期查看本隐私政策以了解任何更改。本隐私政策的更改在发布在此页面上时生效。',
        'privacy.section7.title': '联系我们',
        'privacy.section7.p1': '如果您对此隐私政策有任何疑问，请通过以下方式联系我们：',
		 'privacy.section7.li2.link': '联系我',
        'privacy.section7.li1': '通过电子邮件：lihuigame888@163.com',
        'privacy.section7.li2': '通过访问我网站上的此页面：',
        'privacy.lastUpdated': '最后更新：2025年6月15日',
        
        // 联系区域
        'contact.title': '联系我',
        'contact.subtitle': '有问题或想合作？与我取得联系。',
        'contact.form.name': '姓名',
        'contact.form.namePlaceholder': '您的姓名',
        'contact.form.email': '邮箱',
        'contact.form.emailPlaceholder': '您的邮箱',
        'contact.form.subject': '主题',
        'contact.form.subjectPlaceholder': '主题',
        'contact.form.message': '消息',
        'contact.form.messagePlaceholder': '您的消息',
        'contact.form.submit': '发送消息',
        
        // 页脚
        'footer.description': '创造沉浸式游戏体验，吸引玩家并突破创新边界。',
        'footer.quickLinks': '快速链接',
        'footer.support': '支持',
        'footer.faq': '常见问题',
        'footer.terms': '服务条款',
        'footer.careers': '招聘信息',
        'footer.contactInfo': '联系信息',
        'footer.rights': '保留所有权利。'
    }
};